#pragma once
enum ShipAcceleration{ MOVEMENT_FORWARD, MOVEMENT_BACK, MOVEMENT_LEFT, MOVEMENT_RIGHT, MOVEMENT_UP, MOVEMENT_DOWN, MOVEMENT_NONE};

enum ShipRotation {ROTATION_LEFT, ROTATION_RIGHT, ROTATION_NONE};